<?php

use yii\helpers\Html;
use kartik\form\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
 * @var yii\web\View $this
 * @var app\models\Rubrics $model
 * @var yii\widgets\ActiveForm $form
 * @var string $relAttributes relation fields names for disabling
 */
$listRubrics = [];
?>

<div class="rubrics-form">

    <?php $form = ActiveForm::begin([
            'id' => 'Rubrics',
            'enableClientValidation' => true,
            'errorSummaryCssClass' => 'error-summary alert alert-error'
        ]
    );
    ?>

    <div class="">

        <p>

            <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
            <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
            $form->field($model, 'id_parent')->dropDownList(\app\models\Rubrics::listAllFormatted($listRubrics),
                [
                    'prompt' => '[Корневая рубрика]',
                    'disabled' => (isset($relAttributes) && isset($relAttributes['id_parent'])),
                ]
            ); ?>
        </p>

        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
            '<span class="glyphicon glyphicon-check"></span> ' .
            ($model->isNewRecord ? 'Добавить' : 'Сохранить'),
            [
                'id' => 'save-' . $model->formName(),
                'class' => 'btn btn-success'
            ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

